KarlaCSF/Mini-Asaas

- grails-app/domain/Address.groovy
- src/main/groovy/utils/PersonEntity.groovy
> Feat: Add role blank:false in attributes required on domain

- grails-app/views/customer/index.gsp
- grails-app/views/payer/index.gsp
- src/main/groovy/com/mini/asaas/enums/States.groovy
Agora o campo de Estado é uma lista previamente definida pelo enum States
> refactor: change state field to enum list

- grails-app/controllers/com/mini/asaas/CustomerController.groovy
- grails-app/controllers/com/mini/asaas/PayerController.groovy
- grails-app/domain/com/mini/asaas/Address.groovy
- grails-app/domain/com/mini/asaas/Customer.groovy
- grails-app/domain/com/mini/asaas/Payer.groovy
- grails-app/services/com/mini/asaas/AddressService.groovy
- grails-app/services/com/mini/asaas/CustomerService.groovy
- grails-app/services/com/mini/asaas/PayerService.groovy
- src/main/groovy/com/mini/asaas/dto/AddressDTO.groovy
- src/main/groovy/com/mini/asaas/dto/CustomerDTO.groovy
- src/main/groovy/com/mini/asaas/dto/PayerDTO.groovy
- src/main/groovy/com/mini/asaas/enums/PersonType.groovy
- src/main/groovy/com/mini/asaas/utils/BaseEntity.groovy
- src/main/groovy/com/mini/asaas/utils/PersonEntity.groovy
Adiciona a anotação @GrailsCompileStatic em todas as classes
> add GrailsCompileStatic to classes

- grails-app/domain/com/mini/asaas/payment/Payment.groovy
- grails-app/services/com/mini/asaas/payment/PaymentService.groovy
- src/main/groovy/com/mini/asaas/dto/payment/CreatePaymentDTO.groovy
- src/main/groovy/com/mini/asaas/dto/payment/UpdatePaymentDTO.groovy
- src/main/groovy/com/mini/asaas/enums/payment/BillingType.groovy
- src/main/groovy/com/mini/asaas/enums/payment/PaymentStatus.groovy
- src/main/groovy/com/mini/asaas/utils/ParseUtil.groovy
> build: add annotation @GrailsCompileStatic on Payment

- grails-app/conf/application.yml
- src/main/groovy/com/mini/asaas/utils/PersonEntity.groovy
https://asaasdev.atlassian.net/browse/PMAKES-29
> Atualização automática do campo lastUpdated sempre que um campo for atualizado

- grails-app/controllers/com/mini/asaas/payer/PayerController.groovy
- grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
- grails-app/domain/com/mini/asaas/payer/Payer.groovy
- grails-app/domain/com/mini/asaas/payment/Payment.groovy
- grails-app/services/com/mini/asaas/payer/PayerService.groovy
- grails-app/services/com/mini/asaas/payment/PaymentService.groovy
- grails-app/views/payment/index.gsp
- src/main/groovy/com/mini/asaas/dto/payer/PayerDTO.groovy
> refactor: Payer packages per context

- grails-app/controllers/com/mini/asaas/customer/CustomerController.groovy
> hotfix/import AdressService in CustomerController

- grails-app/services/com/mini/asaas/customer/CustomerService.groovy
- grails-app/services/com/mini/asaas/payer/PayerService.groovy
- src/main/groovy/com/mini/asaas/dto/payment/CreatePaymentDTO.groovy
- src/main/groovy/com/mini/asaas/utils/CpfCnpjUtils.groovy
- src/main/groovy/com/mini/asaas/utils/StringUtils.groovy
- src/main/groovy/com/mini/asaas/utils/Util.groovy
> rename (StringUtils) : create StringUtils to manipulate strings

- src/main/groovy/com/mini/asaas/utils/DateUtils.groovy
- src/main/groovy/com/mini/asaas/utils/StringUtils.groovy
> feat (Payment) : create Date Utils and add method to format currency

- grails-app/assets/stylesheets/main.css
- grails-app/taglib/com/mini/asaas/atlas/AtlasFormTagLib.groovy
- grails-app/views/atlas/forms/_optionList.gsp
- grails-app/views/layouts/main.gsp
> Adicionando configuração para utilizarmos o Atlas e uma AtlasFormTagLib 

- grails-app/controllers/com/mini/asaas/customer/CustomerController.groovy
- grails-app/controllers/com/mini/asaas/invoice/InvoiceController.groovy
- grails-app/controllers/com/mini/asaas/payer/PayerController.groovy
- grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
- grails-app/services/com/mini/asaas/customer/CustomerService.groovy
- grails-app/services/com/mini/asaas/payer/PayerService.groovy
- grails-app/services/com/mini/asaas/payment/PaymentService.groovy
- src/main/groovy/com/mini/asaas/repositories/CustomerRepository.groovy
- src/main/groovy/com/mini/asaas/repositories/PaymentRepository.groovy
> refactor : substituindo consultas com get() e where() e usando as services para buscar dados 

- grails-app/controllers/com/mini/asaas/notification/NotificationController.groovy
- grails-app/domain/com/mini/asaas/notification/Notification.groovy
- grails-app/services/com/mini/asaas/notification/NotificationService.groovy
- grails-app/services/com/mini/asaas/payment/PaymentService.groovy
- grails-app/views/notification/index.gsp
- src/main/groovy/com/mini/asaas/repositories/NotificationRepository.groovy
> Notify Domain

- src/main/groovy/com/mini/asaas/repositories/NotificationRepository.groovy
> Hotfix : queries erradas em NotificationRepository e adição de método para contar quantas notificações não foram lidas 

- grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
> Método para confirmar o pagamento de uma cobrança em dinheiro na controller do payment

- grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
- grails-app/views/layouts/main.gsp
- grails-app/views/templates/_avatar.gsp
- grails-app/views/templates/_header.gsp
- grails-app/views/templates/_notification.gsp
- grails-app/views/templates/_sidebar.gsp
###
- Depois do deploy: usar o método para pegar o atual user e substituir o user fixo
> Adicionando Header e SideBar

- grails-app/views/notFound.gsp
> Estilizando Página de Not Found 

- src/main/groovy/com/mini/asaas/repositories/PayerRepository.groovy
- src/main/groovy/com/mini/asaas/repositories/PaymentRepository.groovy
> Adicionando métodos para contar payers e payments

- src/main/groovy/com/mini/asaas/utils/StringUtils.groovy
> Corrigindo método que deveria limpar caracteres não numéricos e adicionando método para remover não númericos mantendo pontuação

- grails-app/services/com/mini/asaas/address/AddressService.groovy
> Persistencia de cep sem pontuação

- grails-app/controllers/com/mini/asaas/customer/CustomerController.groovy
- grails-app/services/com/mini/asaas/email/EmailService.groovy
- grails-app/views/email/NewUser.gsp
- src/main/groovy/com/mini/asaas/enums/email/EmailTemplateType.groovy
- Envio de notificação ao adicionar um novo usuário a uma conta.
https://github.com/KarlaCSF/Mini-Asaas/pull/44
> Envio de email para novo usuario adicionado

- grails-app/controllers/com/mini/asaas/payment/PaymentController.groovy
- grails-app/views/layouts/main.gsp
- grails-app/views/payment/create.gsp
- grails-app/views/payment/edit.gsp
- grails-app/views/payment/index.gsp
- grails-app/views/payment/list.gsp
- grails-app/views/payment/show.gsp
- src/main/groovy/com/mini/asaas/dto/payment/UpdatePaymentDTO.groovy
> Adicionando flash message no layout main
